[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' cdn.jsdelivr.net;img-src 'self' data:"
    X-Frame-Options = "DENY"
