[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline'; connect-src 'self' 'unsafe-inline' https://furcation.org.uk https://events.furcation.org.uk https://*.ytimg.com wss://ome.knightmare.org.uk:3334 https://*.twitter.com https://api.countapi.xyz; font-src 'self' data:; img-src 'self' data: https://events.furcation.org.uk https://*.ytimg.com https://*.twitter.com; frame-src 'self' https://www.youtube.com https://*.twitter.com; script-src 'self' 'unsafe-inline' https://events.furcation.org.uk https://*.twitter.com;"
    X-Frame-Options = "DENY"

[[redirects]]
  from = "/media/videos/rss"
  to = "https://www.youtube.com/feeds/videos.xml?channel_id=UC9OQo9ZCkFUzLRY18a8SimA"
  status = 200
  force = true
