[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline'; connect-src 'self' 'unsafe-inline' https://events.furcation.org.uk https://*.ytimg.com wss://ome.knightmare.org.uk:3334; font-src 'self' data:; img-src 'self' data: https://events.furcation.org.uk https://*.ytimg.com; frame-src 'self' https://www.youtube.com https://platform.twitter.com; script-src 'self' 'unsafe-inline' https://events.furcation.org.uk https://platform.twitter.com;"
    X-Frame-Options = "DENY"
